<?php

namespace Tests\infra\EloquentRepository;

use App\Domain\Model\FuelEconomy\FuelEconomy;
use App\Domain\Model\FuelEconomy\Refueling;
use App\infra\EloquentRepository\RefuelingEloquentRepository;
//use PHPUnit\Framework\TestCase;
use App\infra\EloquentRepository\RefuelingModelBuilder;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class RefuelingEloquentRepositoryTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $pdo = DB::getPdo();
        $stmt = $pdo->prepare('truncate refuelings');
        $stmt->execute();

    }

    /**
     * @throws \Exception
     */
    public function test_save(){
        $elqRefuelingRepository = new RefuelingEloquentRepository();
        $refueling = new Refueling(null,
            new FuelEconomy(30,450),
            'hanna','jikka');
        $elqRefuelingRepository->save($refueling);

        $refueling2 = new Refueling(null,
            new FuelEconomy(31,500),
            'miki','ryokou');
        $elqRefuelingRepository->save($refueling2);


        $refueling2 = $elqRefuelingRepository->find(2);
        $this->assertTrue( $refueling2 instanceof Refueling);


        // Reflectionクラスをインスタンス化
        $reflectionClass = new \ReflectionClass($refueling2);
        // プロパティの値を取得
        $p_memo = $reflectionClass->getProperty('memo');
        // privateプロパティのアクセス範囲を設定（trueを指定でアクセスできるようになる）
        $p_memo->setAccessible(true);
        $p_memo_value = $p_memo->getValue($refueling2);
        $this->assertSame( 'ryokou',$p_memo_value);


        $refueling2->updateMemo('bonyasumi,tes');

        $p_memo_value = $p_memo->getValue($refueling2);
        $this->assertSame( 'bonyasumi,tes',$p_memo_value);

        $elqRefuelingRepository->save($refueling2);
    }
}
