<?php

namespace Tests\infra\EloquentRepository;

use App\Domain\Model\FuelEconomy\FuelEconomy;
use App\Domain\Model\FuelEconomy\IRefuelingRepository;
use App\Domain\Model\FuelEconomy\Refueling;
use App\infra\EloquentRepository\RefuelingEloquentRepository;
//use PHPUnit\Framework\TestCase;
use App\infra\EloquentRepository\RefuelingModelBuilder;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class RefuelingEloquentRepositoryTest extends TestCase
{

    private IRefuelingRepository $elqRefuelingRepository;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $pdo = DB::getPdo();
        $stmt = $pdo->prepare('truncate refuelings');
        $stmt->execute();
        $this->elqRefuelingRepository = new RefuelingEloquentRepository();

    }

    protected function tearDown(): void
    {
//        $pdo = DB::getPdo();
//        $stmt = $pdo->prepare('truncate refuelings');
//        $stmt->execute();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Exception
     */
    public function test_save(){

        $refueling = new Refueling(null, 1, new \DateTime(),
            new FuelEconomy(30,450),
            'gasStation1','memo1');
        $this->elqRefuelingRepository->save($refueling);

        $refueling2 = new Refueling(null, 1, new \DateTime(),
            new FuelEconomy(31,500),
            'gasStation2','memo2');
        $this->elqRefuelingRepository->save($refueling2);


        $refueling2 = $this->elqRefuelingRepository->find(2);
        $this->assertTrue( $refueling2 instanceof Refueling);

        // Reflectionクラスをインスタンス化
        $reflectionClass = new \ReflectionClass($refueling2);
        // プロパティの値を取得
        $p_memo = $reflectionClass->getProperty('memo');
        // privateプロパティのアクセス範囲を設定（trueを指定でアクセスできるようになる）
        $p_memo->setAccessible(true);
        $p_memo_value = $p_memo->getValue($refueling2);
        $this->assertSame( 'memo2',$p_memo_value);

        sleep(1);

        $refueling2->updateMemo('memo2_modify');
        $p_memo_value = $p_memo->getValue($refueling2);
        $this->assertSame( 'memo2_modify',$p_memo_value);

        $this->elqRefuelingRepository->save($refueling2);

        $refueling = new Refueling(null, 1, new \DateTime(),
            new FuelEconomy(30,450),
            'gasStation1','memo３');
        $this->elqRefuelingRepository->save($refueling);

        return true;
    }
}
