version: '3'

volumes:
  db_data_volume:
    external:
      name: ${MYSQL_VOLUME_NAME}

networks:
  lifenetwork:

services:
  db:
    networks:
      - $CONTAINER_NETWORK
    image: ${MYSQL_IMAGE_NAME}
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - TZ=Asia/Tokyo
      - BIND-ADDRESS=0.0.0.0
    volumes:
      - db_data_volume:/var/lib/mysql
      - ./docker_config/mysql_db/my.cnf:/etc/mysql/my.cnf
    ports:
      - "30306:3306"
    tty: true
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  mail:
    networks:
      - ${CONTAINER_NETWORK}
    image: "mailhog/mailhog"
    container_name: ${MAILHOG_CONTAINER_NAME}
    ports:
      - "8025:8025"
    tty: true

  web:
    networks:
      - ${CONTAINER_NETWORK}
    image: ${WEB_IMAGE_NAME}
    container_name: ${WEB_CONTAINER_NAME}
    environment:
      - DB_PASSWORD=${DB_PASS}
    ports:
      - "9000:80"
    volumes:
      - ./:/opt
    working_dir: /opt
    tty: true
    entrypoint: /bin/sh
    command: >
      -c "
      deluser www-data;
      adduser -u 1000 -s /sbin/nologin -D www-data;
      addgroup nginx www-data ;
      addgroup www-data www-data;
      nginx;docker-php-entrypoint php-fpm
      "

  nodejs:
    container_name: ${NODEJS_CONTAINER_NAME}
    image: ${NODEJS_IMAGE_NAME}
    working_dir: /opt/react_app
    volumes:
      - ./:/opt
    user: ${LOCAL_USER_ID}
    tty: true



