version: '3'

volumes:
  db_data_volume:

services:
  db:
    image: mysql:8.0.24
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - TZ=Asia/Tokyo
      - BIND-ADDRESS=0.0.0.0
    volumes:
      - db_data_volume:/var/lib/mysql
      - ./docker_config/mysql_db/my.cnf:/etc/mysql/my.cnf
    ports:
      - "30306:3306"
    tty: true
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  mail:
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"
    tty: true

  web:
    build:
      context: docker_config/php-fpm_nginx
      dockerfile: Dockerfile
    environment:
      - DB_PASSWORD=${DB_PASS}
    ports:
      - "9000:80"
    volumes:
      - ./:/opt
    working_dir: /opt
    tty: true
    entrypoint: /bin/sh
    command: >
      -c "
      deluser www-data;
      adduser -u 1000 -s /sbin/nologin -D www-data;
      addgroup nginx www-data ;
      addgroup www-data www-data;
      nginx;docker-php-entrypoint php-fpm
      "

  nodejs:
    image: node:14.16.1-alpine
    working_dir: /opt/react_app
    volumes:
      - ./:/opt
    user: ${LOCAL_USER_ID}
    tty: true



