<?php

namespace Tests\infra\Repository;

use App\Domain\Object\Person\Name;
use App\Domain\Object\Person\Person;
use App\Domain\Object\Person\Sex;
use App\Domain\Repository\IPersonRepository;
use App\infra\Repository\InmemoryPersonRepository;
use PHPUnit\Framework\TestCase;

class InmemoryPersonRepositoryTest extends TestCase
{

    private IPersonRepository $personRepository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->personRepository = new InmemoryPersonRepository();
    }

    /**
     * @test
     * @throws \Exception
     */
    public function Person_save(){

        $person = new Person(
            null,
            new Name('山田','花子'),
            (new \DateTime())->setDate(2021,5,31),
            new Sex(1)
        );
        $this->personRepository->save( $person );
        $person = new Person(
            null,
            new Name('山田','太郎'),
            (new \DateTime())->setDate(2000,1,1),
            new Sex(1)
        );
        $this->personRepository->save( $person );

        $person = $this->personRepository->find(1);
        $this->assertSame('山田 花子', $person->getFullName() );
        $person = $this->personRepository->find(2);
        $this->assertSame('2000-01-01', $person->getBornOn() );

        $this->assertNull($this->personRepository->find(3));
    }
}
