<?php

namespace Tests\Application\HouseholdAccount\service;

use App\Application\HouseholdAccount\QueryModel\TransactionViewModel;
use App\Application\HouseholdAccount\service\TransactionRegisterService;
use App\Application\HouseholdAccount\service\TransactionViewService;
use App\Domain\HouseholdAccount\Model\Transaction\Transaction;
use App\Domain\HouseholdAccount\Model\Transaction\TransactionType;
use App\Models\HouseholdAccount\EloquentAccountBalance;
use App\Models\HouseholdAccount\EloquentAccout;
use App\Models\HouseholdAccount\EloquentTransaction;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Str;
//use PHPUnit\Framework\TestCase;
use Tests\TestCase;

class TransactionViewServiceTest extends TestCase
{
    use RefreshDatabase;

    private TransactionViewService $transactionViewService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->transactionViewService = app()->make(TransactionViewService::class);;

        $userId = 1;
        $transaction_id = (string)Str::orderedUuid();
        $transaction1 = EloquentTransaction::create([
            'transaction_id' => $transaction_id,
            'user_id' => $userId,
            'date' => (new \DateTime())->format('Y-m-d'),
            'amount' => 100,
            'contents' => '',
            'type' => TransactionType::CLASSIFICATION_ACCOUNT_TRANSFER
        ]);

        EloquentAccountBalance::create([
            'transaction_id' => $transaction_id,
            'account_id' => 1,
            'balance' => 100000,
        ]);

        EloquentAccountBalance::create([
            'transaction_id' => $transaction_id,
            'account_id' => 2,
            'balance' => 100000,
        ]);

        EloquentAccout::create([
            'account_id'=>1,
            'user_id'=>$userId,
            'type'=>1,
            'name'=>"hoge",
        ]);
        EloquentAccout::create([
            'account_id'=>2,
            'user_id'=>$userId,
            'type'=>1,
            'name'=>"hoge",
        ]);

    }

    public function test_do(){

        /** @var TransactionViewModel[] $transactionViewModelList */
        $transactionViewModelList = $this->transactionViewService->do($user_id=1);

    }
}
